include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - web/**
    - android/**
    - ios/**
    - tool/sample_scenes/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - prefer_final_locals
    - prefer_single_quotes
    - avoid_dynamic_calls
    - unawaited_futures
